name: deepjet
channels:
- NLeSC
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- fftw=3.3.4=0
- gsl=1.16=2
- pcre=8.35=7
- root=6.04=py3.4_clang503
- root-numpy=4.4.0=root6.04_py3.4
- h5py=2.6.0=np111py34_7
- hdf5=1.8.17=9
- libgfortran=3.0.0=0
- mock=2.0.0=py34_0
- pbr=1.10.0=py34_0
- protobuf=3.1.0=py34_0
- pyyaml=3.11=py34_0
- six=1.10.0=py34_1
- tensorflow=0.12.1=py34_1
- theano=0.8.2=py34_0
- yaml=0.1.6=0
- appnope=0.1.0=py34_0
- cycler=0.10.0=py34_0
- decorator=4.0.11=py34_0
- freetype=2.5.5=2
- icu=54.1=0
- ipython=5.1.0=py34_1
- ipython_genutils=0.1.0=py34_0
- krb5=1.13.2=0
- libiconv=1.14=0
- libpng=1.6.27=0
- libxml2=2.9.4=0
- matplotlib=2.0.0=np111py34_0
- mkl=2017.0.1=0
- numexpr=2.6.1=np111py34_2
- numpy=1.11.3=py34_0
- openssl=1.0.2k=0
- path.py=10.0=py34_0
- pexpect=4.2.1=py34_0
- pickleshare=0.7.4=py34_0
- pip=9.0.1=py34_1
- prompt_toolkit=1.0.9=py34_0
- ptyprocess=0.5.1=py34_0
- pygments=2.1.3=py34_0
- pyparsing=2.1.4=py34_0
- pyqt=5.6.0=py34_2
- pytables=3.3.0=np111py34_0
- python=3.4.5=0
- python-dateutil=2.6.0=py34_0
- pytz=2016.10=py34_0
- qt=5.6.2=0
- readline=6.2=2
- scipy=0.18.1=np111py34_1
- setuptools=27.2.0=py34_0
- simplegeneric=0.8.1=py34_1
- sip=4.18=py34_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.3.1=py34_0
- wcwidth=0.1.7=py34_0
- wheel=0.29.0=py34_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - keras==1.2.1
  - prompt-toolkit==1.0.9
  - tables==3.3.0

